export const UNIT_NAMES = { 
  infantry: [ 
    "DE 113e Schutzen" 
    ,"DE 141e GebirGsager" 
    ,"DE 1er régiment" 
    ,"DE 22e régiment" 
    ,"DE 28e régiment Jager" 
    ,"DE 2e régiment mortier" 
    ,"DE 35e Grenadier" 
    ,"DE 361e régiment Afrique" 
    ,"DE 3e Fallschirmjager" 
    ,"DE 432e régiment" 
    ,"DE 4e Baraillon de pionniers" 
    ,"DE 50e régiment" 
    ,"DE 59e PanzerGrenadier" 
    ,"DE 738e régiment de Jager" 
    ,"DE 87e grenadier" 
    ,"DE 957e volksgrenadier" 
    ,"DE 980e Volkgrenadier" 
    ,"DE bataillon Bergmann" 
    ,"DE Gerbirgs-pionnier 95" 
    ,"FN bataillon cotier 7" 
    ,"FN bataillon détaché 4" 
    ,"FN Bataillon jager 2" 
    ,"FN détachement léger 15" 
    ,"FN Ryhma SUSI" 
    ,"FN régiment 13" 
    ,"FN régiment 25" 
    ,"FN régiment 61" 
    ,"FN SISSI 1" 
    ,"FN SISSI 2" 
    ,"FR 110e régiment motorisé" 
    ,"FR 13e Dragons" 
    ,"FR 152e régiment" 
    ,"FR 1er BCP" 
    ,"FR 1er Hussards" 
    ,"FR 1er régiment étranger" 
    ,"FR 2e RMT" 
    ,"FR 43e régiment motorisé" 
    ,"FR 4e brigade" 
    ,"FR 51e régiment" 
    ,"FR 73e régiment" 
    ,"FR commandos Kieffer" 
    ,"FR corps exp" 
    ,"FR FFI" 
    ,"IT 185e Folgore" 
    ,"IT 186e Folgore" 
    ,"IT 2e régiment" 
    ,"IT 39e régiment de Bologne" 
    ,"IT 3e régiment" 
    ,"IT 76e Napoli" 
    ,"IT 80e pasubio" 
    ,"IT 9e bersagliers" 
    ,"IT division Trento" 
    ,"IT savoia cavalleria" 
    ,"JP 10e re REC" 
    ,"JP 118e régiment" 
    ,"JP 15e régiment" 
    ,"JP 174e indépendant" 
    ,"JP 24e régiment" 
    ,"JP 33e de REC" 
    ,"JP 58e régiment" 
    ,"JP 5e régiment" 
    ,"JP 70e régiment" 
    ,"JP division tempete" 
    ,"PL 10e légion" 
    ,"PL 16e régiment de TArnow" 
    ,"PL 35e régiment" 
    ,"PL 3e des Carpates" 
    ,"PL 3e régiment" 
    ,"PL 5e régiment des légions" 
    ,"PL 6e régiment antichar" 
    ,"PL 74e régiment de Silésie" 
    ,"PL division Zaza" 
    ,"SV 101e de bezhitsa" 
    ,"SV 128e régiment de fusiliers" 
    ,"SV 12e garde" 
    ,"SV 15e régiment ski" 
    ,"SV 178e fusiliers" 
    ,"SV 266e fusiliers de la garde" 
    ,"SV 2e fusiliers marins" 
    ,"SV 329e bataillon du génie" 
    ,"SV 38e fusilier" 
    ,"SV 456e régiment de fusiliers" 
    ,"SV 4e cosaques de Kouban" 
    ,"SV 573e régiment de fusiliers" 
    ,"SV 676e régiment" 
    ,"SV 6e régiment" 
    ,"SV 756e régiment" 
    ,"SV 99e Kholm" 
    ,"UK 105e brigade" 
    ,"UK 10e mortar" 
    ,"UK 15e PECCE" 
    ,"UK 22e brigade de la garde" 
    ,"UK 30e brigade" 
    ,"UK 7e Scottish borderers" 
    ,"UK 85e compagnie de pionners" 
    ,"UK bataillon parachutiste" 
    ,"UK bloody eleventh" 
    ,"UK Commando n10" 
    ,"UK Green Howards" 
    ,"UK Guardes grenadiers" 
    ,"UK Highlanders Argyllshire" 
    ,"UK Kings african rifles" 
    ,"UK Layforce" 
    ,"UK Lovat Scouts" 
    ,"UK Ours polaires" 
    ,"UK OX and Bucks" 
    ,"UK Royal Marine" 
    ,"UK Royal scots" 
    ,"UK sherwood foresters" 
    ,"US 109e ingénieur militaires" 
    ,"US 10e bataillon du génie" 
    ,"US 133e ironman" 
    ,"US 179e Tomahawks" 
    ,"US 22e marines" 
    ,"US 2e Michigan" 
    ,"US 32e régiment" 
    ,"US 463e bataillon" 
    ,"US 506e régiment" 
    ,"US 507e para" 
    ,"US 511e aéroportée" 
    ,"US 5e rangers" 
    ,"US 5e régiment" 
    ,"US 60e régiment" 
    ,"US 7e régiment" 
    ,"US 99e bataillon" 
    ,"US Diables rouges" 
    ,"US recon US" 
    ,"US the deuce" 
    ,"US the professionals" 
  ], 
  tank: [ 
    "DE elephant tank" 
    ,"DE Flammpanzer" 
    ,"DE Grief" 
    ,"DE Jagdpanther" 
    ,"DE Panther G" 
    ,"DE panzer 35(t)" 
    ,"DE Panzer I-B" 
    ,"DE Panzer II-A" 
    ,"DE Panzer III-F" 
    ,"DE PAnzer III-G" 
    ,"DE panzer III-J" 
    ,"DE Panzer IV" 
    ,"DE Sd Kfs 250" 
    ,"DE Sd Kfz 10 Pak 38" 
    ,"DE Sd Kfz 222" 
    ,"DE Stug III G Schurzen" 
    ,"DE Stug III-F" 
    ,"DE STUG IV" 
    ,"DE Tiger I-E" 
    ,"FN Sturmi" 
    ,"FN T-26 FI" 
    ,"FR 176 panhard" 
    ,"FR char B1 bis" 
    ,"FR Hotchkiss h35" 
    ,"FR Somua s35" 
    ,"IT 33e régiment" 
    ,"IT L640" 
    ,"IT M1340" 
    ,"IT semovento DA75" 
    ,"JP modèle 125" 
    ,"JP type 3 Chi-Nu" 
    ,"JP type 4 Chi-To" 
    ,"JP type 92 Jyu" 
    ,"JP type 93" 
    ,"JP type 94 TK" 
    ,"JP type 95 Ha-Go" 
    ,"JP type 97 Chi-Ha" 
    ,"JP type 97 Shinhoto" 
    ,"JP type 98 Ke-Ni" 
    ,"PL 24e Ulan" 
    ,"PL 4TP" 
    ,"PL 7TP" 
    ,"PL M4 Sherman" 
    ,"PL T-34 76" 
    ,"PL TKS" 
    ,"SV BT-7 1937" 
    ,"SV BT-7" 
    ,"SV I0SEF Stalin II" 
    ,"SV ISU-152" 
    ,"SV KV-1 1941" 
    ,"SV KV-1S" 
    ,"SV KV-2" 
    ,"SV KV-85" 
    ,"SV SU 152" 
    ,"SV SU-100" 
    ,"SV SU-76m" 
    ,"SV T-34 1942" 
    ,"SV T-35" 
    ,"SV T-60" 
    ,"SV T-70" 
    ,"UK A34 Comet" 
    ,"UK Churchill Mk III Avre" 
    ,"UK Churchill Mk IV " 
    ,"UK cruiser Mk III" 
    ,"UK Crusader Mk II" 
    ,"UK Humber Mk II" 
    ,"UK Humber Mk IV" 
    ,"UK M3 Grant" 
    ,"UK M3A3 Honey" 
    ,"UK M4 Firefly" 
    ,"UK Matilda Mk IV" 
    ,"UK Valentine Mk II" 
    ,"US 7e renf" 
    ,"US M10 Wolverine" 
    ,"US M10A1" 
    ,"US M20 Scout car" 
    ,"US M26 Pershing" 
    ,"US M3 LEE" 
    ,"US M4 Sherman" 
    ,"US M4A1" 
    ,"US M4A3R3 Zippo" 
    ,"US M5 Stuart" 
    ,"US M6" 
    ,"US M8 Greyhound" 
  ], 
  artillery: [ 
    "DE autokanon 87" 
    ,"DE Flak 88" 
    ,"DE Hummel" 
    ,"DE leFH de" 
    ,"DE Leopold" 
    ,"DE Mardrer III H" 
    ,"DE Nebelwerfer" 
    ,"DE PAK 36" 
    ,"DE Pak 40" 
    ,"DE Wespe" 
    ,"FN PAK 36 FI" 
    ,"FR 155 C modèle 1917" 
    ,"FR canon de 75" 
    ,"IT cannone DA47" 
    ,"IT Obice DA 75" 
    ,"JP artillerie campagne 75mm" 
    ,"JP canon AA type 88" 
    ,"JP canon de campagne 105mm" 
    ,"JP canon de montagne 75mm" 
    ,"JP obusier cotier 28mm" 
    ,"JP type 1 37mm" 
    ,"JP type 4 Ho-Ro" 
    ,"PL batterie cotière" 
    ,"PL canon Bofors 37mm" 
    ,"SV 52-K" 
    ,"SV canon antiaérien 37mm" 
    ,"SV canon antichar 45mm" 
    ,"SV canon de campgane D-44" 
    ,"SV Katyusha" 
    ,"SV obusier B-4 203mm" 
    ,"SV obusier canon 152mm" 
    ,"SV obusier de 1939 76mm" 
    ,"SV Zis-2" 
    ,"UK 2 Pounder" 
    ,"UK 6 Pounder" 
    ,"UK BL 4.5 pouces" 
    ,"UK canon cotier 9.2p" 
    ,"UK QF Mk III 40 mm" 
    ,"UK Sexton" 
    ,"US 105mm Howitzer" 
    ,"US calliope" 
    ,"US canon M1 de 120mm" 
    ,"US M5 de 3 pouces" 
    ,"US M7 Priest" 
    ,"US M8 Howitzer" 
    ,"US modèle 1918 155mm" 
    ,"US obusier pack 75mm" 
    ,"US T19 Howitzer" 
  ], 
  train: [ 
    "DE panzerzug 61 BP42" 
    ,"PL Danuta" 
    ,"SV Train blindé" 
  ], 
  sniper: [ 
    "DE 119e grenadier" 
    ,"DE 92e régiment" 
    ,"FN La mort blanche" 
    ,"FR 27e DIA" 
    ,"JP régiment Toyoma" 
    ,"SV 289e Gatchina" 
    ,"SV 6e régiments de fusiliers" 
    ,"UK elite 52e" 
    ,"US 47e régiment" 
  ], 
  boat: [ 
    "DE KM Prinz Eugen" 
    ,"DE KM Tirpitz" 
    ,"JP Ijn Akagi" 
    ,"JP Ijn Mikura" 
    ,"PL general Haller" 
    ,"UK HMS Belfast" 
    ,"US USS Fitch" 
    ,"US USS MIssouri" 
    ,"US USS night" 
    ,"US USS Yorktown" 
  ], 
}; 
